services:
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - hybrid-service-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_HEALTH_DISCOVERY_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS=always
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - hybrid-service-network
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_ENABLED=true
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=20
      - SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL=5000
      - SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL=20000
      - SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER=1.5
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9000:9000"
    networks:
      - hybrid-service-network
    depends_on:
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=9000
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=20
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: senha123
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: true
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    command: start-dev
    networks:
      - hybrid-service-network
  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=senha123
    networks:
      - hybrid-service-network
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres:16
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_USER_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_USER_SERVICE}
      POSTGRES_DB: user_service_db
    ports:
      - "5432:5432"
    networks:
      - hybrid-service-network
    volumes:
      - pg-data-user-service:/var/lib/postgresql/data
  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME_USER_SERVICE}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD_USER_SERVICE}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=20
    networks:
      - hybrid-service-network
    depends_on:
      - user-db
      - config-server
      - discovery-server

  taxi-db:
    image: postgres:16
    container_name: taxi-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_TAXI_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TAXI_SERVICE}
      POSTGRES_DB: taxi_service_db
    ports:
      - "5433:5432"
    networks:
      - hybrid-service-network
    volumes:
      - pg-data-taxi-service:/var/lib/postgresql/data
  taxi-service:
    build: ./taxi-service
    container_name: taxi-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME_TAXI_SERVICE}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD_TAXI_SERVICE}
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=20
    networks:
      - hybrid-service-network
    depends_on:
      - taxi-db
      - config-server
      - discovery-server

  vehicle-service:
    build: ./vehicle-service
    container_name: vehicle-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME_VEHICLE_SERVICE}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD_VEHICLE_SERVICE}
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=20
    networks:
      - hybrid-service-network
    depends_on:
      - vehicle-db
      - config-server
      - discovery-server
  vehicle-db:
    image: postgres:16
    container_name: vehicle-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_VEHICLE_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_VEHICLE_SERVICE}
      POSTGRES_DB: vehicle_service_db
    ports:
      - "5434:5432"
    networks:
      - hybrid-service-network
    volumes:
      - pg-data-vehicle-service:/var/lib/postgresql/data

  driver-service:
    build: ./driver-service
    container_name: driver-service
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME_DRIVER_SERVICE}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD_DRIVER_SERVICE}
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS=20
    networks:
      - hybrid-service-network
    depends_on:
      - driver-db
      - config-server
      - discovery-server
  driver-db:
    image: postgres:16
    container_name: driver-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_DRIVER_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DRIVER_SERVICE}
      POSTGRES_DB: driver_service_db
    ports:
      - "5435:5432"
    networks:
      - hybrid-service-network
    volumes:
      - pg-data-driver-service:/var/lib/postgresql/data

  redis:
    image: redis:8.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    networks:
      - hybrid-service-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'INTERNAL://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 227272be-184e-4b9c-a4d9-8f6fa03e5367
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list" ]
      interval: 30s
      timeout: 5s
      retries: 20
    networks:
      - hybrid-service-network
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: unless-stopped
    ports:
      - "9080:9080"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka
    networks:
      - hybrid-service-network

volumes:
  pg-data-user-service:
  pg-data-taxi-service:
  keycloak-db-data:
  redis-data:
  keycloak-data:
  pg-data-vehicle-service:
  pg-data-driver-service:
networks:
  hybrid-service-network:
    driver: bridge


