spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/auth/realms/hybrid-service-realm

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
