spring:
  application:
    name: user-service
logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG
    com.rezende.user_service.services: DEBUG